#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$ROOT_DIR/scripts/install"
STEPS_DIR="$INSTALL_DIR/steps"
source "$INSTALL_DIR/lib/common"

read_system_pass
read_luks_pass
read_git_config
setup_git_user

STEPS=(
  "$STEPS_DIR/00-setup-pacman"
  "$STEPS_DIR/05-setup-fde"
  "$STEPS_DIR/15-install-packages"
  "$STEPS_DIR/17-setup-dms"
)

for step in "${STEPS[@]}"; do
  if [[ ! -x "$step" ]]; then
    die "Step not found or not executable: $step"
  fi

  log "Running $(basename "$step")"
  bash "$step"
done

cleanup_all

log "Done"
