inherits = "default"

"ui.background" = {}
"ui.text" = { fg = "foreground" }

"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] }

"ui.statusline" = {}
"ui.statusline.inactive" = {}

"ui.popup" = {}
"ui.popup.info" = {}
"ui.help" = {}
"ui.menu" = {}
"ui.menu.scroll" = {}
"ui.window" = {}

"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.selection" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { modifiers = ["underlined"] }

"ui.text.inactive" = { fg = "gray" }
