theme = "myterm"

[editor]
line-number = "relative"
cursorline = false
bufferline = "multiple"
color-modes = true
popup-border = "none"

[editor.statusline]
left = ["mode", "file-name"]
right = ["diagnostics", "position", "file-type"]
