#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common"

log "Installing gaming apps..."

install_package \
  steam \
  prismlauncher \
  faugus-launcher \
  wowup-cf-bin \
  wine \
  winetricks \
  vulkan-icd-loader \
  lib32-vulkan-icd-loader \
  gamemode \
  mangohud \
  lib32-mangohud \
  protonup-qt \
  dosbox \
  inotify-tools \
  scummvm \
  timidity++ \
  wget \
  xdotool \
  xorg-xwininfo \
  yad

require_paru
install_aur_package modrinth-app-bin

log_success "Gaming apps setup complete."
